[phases.setup]
nixPkgs = ["nodejs_20", "pnpm_9"]

[phases.install]
cmds = ["pnpm install"]
cacheDirectories = ["node_modules"]

[phases.build]
cmds = ["pnpm run build"]

[start]
cmd = "npx serve dist -s -l 3000"
